plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'fr.iutrodez.sae501.cliandcollect'
    compileSdk 34

    defaultConfig {
        applicationId "fr.iutrodez.sae501.cliandcollect"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("./CliAndCollect-Key.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: ""
            keyAlias System.getenv("KEY_ALIAS") ?: ""
            keyPassword System.getenv("KEYSTORE_PASSWORD") ?: ""
        }
    }

    buildTypes {
        // ... reste inchangé ...
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation libs.volley
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.viewpager2
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext
    androidTestImplementation libs.androidx.test.espresso.core
    implementation libs.androidx.preference

    // open street map
    implementation libs.osmdroid.android
    implementation libs.osmbonuspack
}

